#!/bin/bash
#  _       _                               __ ____ ____  
# | |     | |                             /_ |___ \___ \ 
# | | ____| | __ ___      _____  ___  _ __ | | __) |__) |
# | |/ / _` |/ _` \ \ /\ / / __|/ _ \| '_ \| ||__ <|__ < 
# |   < (_| | (_| |\ V  V /\__ \ (_) | | | | |___) |__) |
# |_|\_\__,_|\__,_| \_/\_/ |___/\___/|_| |_|_|____/____/ 
#
# https://github.com/kdawson133 @kirk133
#
mount -t smbfs //oxygen/Code /Users/ktdawson/Server/Code
mount -t smbfs //oxygen/Data /Users/ktdawson/Server/Data
mount -t smbfs //oxygen/Media /Users/ktdawson/Server/Media
mount -t smbfs //oxygen/Music /Users/ktdawson/Server/Music
mount -t smbfs //oxygen/Torrents /Users/ktdawson/Server/Torrents
